name: Build for linux

on:
  push:
    branches:
      - master

jobs:
  Building:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Qt5 and the dependencies of the SFML.
        run: sudo apt-get update &&
          sudo apt-get install --yes qt5-default libfreetype6-dev libxrandr-dev libudev-dev libogg-dev libflac-dev libvorbis-dev libopenal-dev freeglut3-dev
      - name: Install the SFML.
        run: |
          git clone https://github.com/SFML/SFML -b 2.5.x /tmp/sfml
          cd /tmp/sfml
          mkdir build
          cd build
          cmake .. && make -j 4 && sudo make install
      - name: Build Makefile with CMake
        run: mkdir -p build && cd build && cmake ..
      - name: Build with Makefile
        run: make -C build ComSquare
      - name: Archive production artifact
        uses: actions/upload-artifact@v1
        with:
          name: ComSquare
          path: build/ComSquare
